### PR TITLE
fix(ui): Use proper URL fragments ("#tab=…", not "#tab%3D…")

### LINKED ISSUE #539: Feature: rewrite URLs so that `%3D` chars are rendered as `=`
### Related user(s):

@erikmd

### Related issue(s) or PR(s):

_No response_

### Related project scope(s):

web-app UI

### The problem:

When opening an exercise in a dynamic learn-ocaml server, the `=` chars are unexpectedly rendered as `%3D`:

* http://localhost:8080/exercises/tp1/#tab%3Dreport

### Wanted solution:

It would be nice to keep the `=` chars as is thanks to URL rewriting (if possible):

* http://localhost:8080/exercises/tp1/#tab=report

### Considered alternatives:

_No response_

### Additional context:

_No response_

### PR DESCRIPTION
**Pull request by erikmd**
* **Kind:** bugfix (workaround)

* Close #539

### Description

Fix #539 while the upstream patch https://github.com/ocsigen/js_of_ocaml/pull/1497 is not used.

### Checklist

* [x] Read the [CONTRIBUTING.md](https://github.com/ocaml-sf/learn-ocaml/blob/master/CONTRIBUTING.md) guide and:
  * [x] Use [Atomic Commits](https://github.com/ocaml-sf/learn-ocaml/blob/master/CONTRIBUTING.md#atomic-commits) so each commit gathers a single logical change
  * [x] Use [Conventional Commits](https://github.com/ocaml-sf/learn-ocaml/blob/master/CONTRIBUTING.md#conventional-commits) regarding commit messages (needed by our release toolchain)

### Note to maintainers

* Read [this wiki page](https://github.com/ocaml-sf/learn-ocaml/wiki/Checklist-for-testing-and-merging-a-PR).
* Make sure the PR has a **milestone**.
* ***Assign*** yourself before merging.
* [ ] Either do a regular **merge**:
  * for PRs containing *several commits* following [conventional-commits](https://github.com/ocaml-sf/learn-ocaml/blob/master/CONTRIBUTING.md#conventional-commits),
  * or for PRs containing 1 commit shared with a later PR (to preserve the SHA1)
* [x] Or do a **squash-merge**:
  * for PRs containing *only 1 commit* (not shared with a later PR),
  * or for PRs containing several commits that need not be kept in the history;
  * → ***Update the commit message header*** with a [conventional-commit type](https://github.com/ocaml-sf/learn-ocaml/blob/master/CONTRIBUTING.md#conventional-commits-examples),
  * → ***Add a footer*** `Close #…` if a related issue exists.

### CODE REVIEW

File: src/utils/js_utils.ml [hunk 1]
```diff
@@ -1201,7 +1201,11 @@ let parse_fragment () =
 let set_fragment args =
   let pairs = List.map (fun (n, v) -> n ^ "=" ^ v) args in
   let fragment = String.concat "&" pairs in
-  Url.Current.set_fragment fragment
+  (* TODO: Replace with
+  {| Url.Current.set_fragment fragment |}
+  when https://github.com/ocsigen/js_of_ocaml/pull/1497 is shipped
```
Comment (yurug) [inline src/utils/js_utils.ml:1206]: Did you create an issue to track this down?

**Comment by yurug** [comment]
LGTM.

File: src/utils/js_utils.ml (hunk 1 above)
Comment (erikmd) [reply src/utils/js_utils.ml:1206]: There is already https://github.com/ocaml-sf/learn-ocaml/issues/539

→ do you suggest that we create yet another issue, more to the point?
→ otherwise, we can just keep #539 and not close it

Comment (erikmd) [reply src/utils/js_utils.ml:1206]: @yurug Anyway, I'm afraid we will wait for a (very) long time before we can do this very small replacement,
because we should wait that js_of_ocaml ships this fix, and that the newest js_of_ocaml release becomes one day the minimal required version in learn-ocaml.

so, not sure it is worth an issue.

WDYT?
