### PR TITLE
fix(learnocaml_common.ml): change secret to token for authentificatio…

### LINKED ISSUE #488: Bug: wrong question asked when browsing a complete exercice URL
**Related project scope(s):** exercise UI

## Bug description

* As a user
* When I am disconnected from a learn-ocaml instance
* And I paste a complete exercice URL such as https://localhost:8080/exercises/demo/
* Then I unexpectedly see the question `Enter the secret` (to create a new account) instead of a more sensible question such as `Enter your token`.

### To reproduce

1. Add a file `demo-repository/server_config.json` containing:
   ```
   {
     "secret": "MDP"
   }
   ```
1. Run a learn-ocaml instance, e.g.  
   `cd ……/learn-ocaml && learn-ocaml build serve --repo=demo-repository`
1. Open a fresh browser instance (e.g., private browsing mode)
1. Go to https://localhost:8080/exercises/demo/
1. Then notice the question `Enter the secret`

### Expected behavior

1. Get the question `Enter your token`

### Optional screenshots

2022-05-24_11-42-19_Screenshot_Secret

## Current configuration

* OS name (and version): N/A
* Browser name (and version): N/A
* `learn-ocaml --version`: 0.14.0

### PR DESCRIPTION
**Pull request by JossyYila**
* **Kind:** bugfix 

* Close #488

### Description

Change secret to token for authentification in Exercise link

### Checklist

* [x] Read the [CONTRIBUTING.md](https://github.com/ocaml-sf/learn-ocaml/blob/master/CONTRIBUTING.md) guide and:
  * [x] Use [Atomic Commits](https://github.com/ocaml-sf/learn-ocaml/blob/master/CONTRIBUTING.md#atomic-commits) so each commit gathers a single logical change
  * [x] Use [Conventional Commits](https://github.com/ocaml-sf/learn-ocaml/blob/master/CONTRIBUTING.md#conventional-commits) regarding commit messages (needed by our release toolchain)
* [ ] Add/update [tests](https://github.com/ocaml-sf/learn-ocaml/tree/master/tests#readme)
  
* [ ] Add/update [documentation](https://github.com/ocaml-sf/learn-ocaml/tree/master/docs)
  
* [ ] …
  

### Note to maintainers

* Read [this wiki page](https://github.com/ocaml-sf/learn-ocaml/wiki/Checklist-for-testing-and-merging-a-PR)
* Make sure the PR has a milestone
* Assign yourself before merging
* We can squash-merge 1-commit PRs (use a header with a [conventional-commit type](https://github.com/ocaml-sf/learn-ocaml/blob/master/CONTRIBUTING.md#conventional-commits-examples), add a footer with `Fix #…` if need be)

### CODE REVIEW

File: src/app/learnocaml_common.ml [hunk 1]
```diff
@@ -1106,17 +1106,23 @@ let get_token ?(has_server = true) () =
     try
       Some Learnocaml_local_storage.(retrieve sync_token) |>
         Lwt.return
-    with Not_found ->
+    with
+    Not_found ->
```
Comment (erikmd) [inline src/app/learnocaml_common.ml:1110]: unneeded refactoring that might be reverted:

```suggestion
    with Not_found ->
```

Comment (erikmd) [reply src/app/learnocaml_common.ml:1110]: but nevermind.

**Review by erikmd — APPROVED** [review]
OK, thanks @JossyYila; I tested the PR successfully so it can be merged as is.
